[theme]
primaryColor = "#1F77B4"            # litt lysere blå for knapper og aksenter
backgroundColor = "#F0F4F8"         # nesten hvit, med et snev av blåtoning
secondaryBackgroundColor = "#E1E8F0" # lys blå bakgrunn for sidebar og kort
textColor = "#333333"               # mørk grå for bedre kontrast
font = "sans serif"
